-- CreateTable
CREATE TABLE "Plumbers" (
    "id" SERIAL NOT NULL,
    "Keyword" TEXT,
    "Name" TEXT,
    "Full_Address" TEXT,
    "Address_1" TEXT,
    "Address_2" TEXT,
    "Address_3" TEXT,
    "Address_4" TEXT,
    "Address_5" TEXT,
    "Website" TEXT,
    "Phone" TEXT,
    "Email" TEXT,
    "Facebook" TEXT,
    "Twitter" TEXT,
    "Instagram" TEXT,
    "Edit_Links" TEXT,
    "Category" TEXT,
    "Rating" DOUBLE PRECISION,
    "Reviews" TEXT,
    "Image_URL" TEXT,
    "Pricing" TEXT,
    "Amenities" TEXT,
    "Description" TEXT,
    "Summary" TEXT,
    "Monday" TEXT,
    "Tuesday" TEXT,
    "Wednesday" TEXT,
    "Thursday" TEXT,
    "Friday" TEXT,
    "Saturday" TEXT,
    "Sunday" TEXT,
    "Services" TEXT,
    "Located_in" TEXT,
    "Attributes" TEXT,
    "Logo" TEXT,
    "Providers_Urls" TEXT,
    "URL" TEXT,
    "SStatus" BOOLEAN,

    CONSTRAINT "Plumbers_pkey" PRIMARY KEY ("id")
);
